export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_ERROR = "GET_QUESTIONS_ERROR";
export const CLICK_ANSWER = "CLICK_ANSWER";
export const GET_THEMES_REQUEST="GET_THEMES_REQUEST";
export const GET_THEMES_SUCCESS="GET_THEMES_SUCCESS";
export const GET_THEMES_ERROR="GET_THEMES_ERROR";
export const CLICK_THEME="CLICK_THEME";