
export const SESSION_AUTH_REQUEST="SESSION_AUTH_REQUEST";
export const SESSION_AUTH_SUCCESS="SESSION_AUTH_SUCCESS";
export const SESSION_AUTH_ERROR="SESSION_AUTH_ERROR";
export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR="REGISTER_USER_ERROR";
export const VALIDATION_FIRST_NAME_REGISTRATION="VALIDATION_FIRST_NAME_REGISTRATION";
export const VALIDATION_LAST_NAME_REGISTRATION="VALIDATION_LAST_NAME_REGISTRATION";
export const VALIDATION_PASSWORD_REGISTRATION="VALIDATION_PASSWORD_REGISTRATION";
export const VALIDATION_LOGIN_REGISTRATION="VALIDATION_LOGIN_REGISTRATION";
export const CHECK_REPEAT_PASSWORD="CHECK_REPEAT_PASSWORD";
